name: ZAP API Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      web:
        image: ghcr.io/ravidaggumati/health-care-management-system-python-fastapi-app:latest
        ports:
          - 8000:8000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for the service to be up
        run: |
          echo "Waiting for the app to start..."
          sleep 15

      - name: Run ZAP with OpenAPI import
        run: |
          docker run -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://localhost:8000 \
            -r zap_report.html \
            -I \
            -j \
            -z "-config replacer.full_list(0).description=authheader -config replacer.full_list(0).enabled=true -config replacer.full_list(0).matchtype=REQ_HEADER -config replacer.full_list(0).matchregex=false -config replacer.full_list(0).matchstring=Authorization -config replacer.full_list(0).replacement=Bearer <token>" \
            -U http://localhost:8000/openapi.json
