name: API Security Test

on:
  push:
    branches: [ "main" ]

jobs:
  zap-api-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build FastAPI Docker image
      run: docker build -t fastapi-app .

    - name: Create Docker network
      run: docker network create zapnet

    - name: Run FastAPI container
      run: docker run -d --rm --name fastapi-app --network zapnet -p 8000:8000 fastapi-app

    - name: Start FastAPI app
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        curl http://localhost:8000/docs || exit 1

    - name: Run ZAP API scan
      run: |
        docker run --rm --network zapnet \
          -v $(pwd):/zap/wrk:rw \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-api-scan.py -t http://fastapi-app:8000/openapi.json -f openapi -r zap_report.html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-api-report
        path: zap_report.html
