name: API Security Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-test:
    runs-on: ubuntu-latest
    services:
      fastapi:
        image: python:3.10
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl --fail http://localhost:8000/docs || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          ENVIRONMENT: github
        volumes:
          - .:/app
        entrypoint: >
          sh -c "
            pip install -r /app/requirements.txt &&
            uvicorn app.main:app --host 0.0.0.0 --port 8000
          "

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for FastAPI to be ready
        run: |
          echo "Waiting for FastAPI app to start..."
          sleep 20
          curl http://localhost:8000/docs || exit 1

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: http://localhost:8000
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          fail_action: false
          allow_issue_writing: true
          artifact_name: zap_scan
